### ISSUE TITLE
Error: cannot open device with path 0001:0025:00 and Module version mismatch. Expected 48, got 57.

### ISSUE THREAD

**Issue by ayush-techracers** [LedgerHQ/ledgerjs#158]
I'm trying to access xpub for a specified path from my ledger device, here's the sample code for what I will eventually do:
```
const ledger = require("ledgerco");
const bip32 = require("bip32");

function getCompressPublicKey(publicKey) {
  let compressedKeyIndex;
  if (parseInt(publicKey.substring(128, 130), 16) % 2 !== 0) {
    compressedKeyIndex = "03";
  } else {
    compressedKeyIndex = "02";
  }
  const result = compressedKeyIndex + publicKey.substring(2, 66);
  return result;
}

ledger.comm_node
  .create_async()
  .then(comm => {
    if (!comm) return console.log("err: Unable to establish connection");

    var btc = new ledger.btc(comm);

    btc
      .getWalletPublicKey_async("44'/0'/0'/0")
      .then(function(result) {
        console.log("Result\n:", result);
        let compressedKey = getCompressPublicKey(result.publicKey);

        publicKey = new Buffer(compressedKey, "hex");
        chaincode = new Buffer(result.chainCode, "hex");
        const a = bip32.fromPublicKey(publicKey, chaincode);

        console.log("xPub:", a.neutered().toBase58());
      })
      .catch(function(error) {
        console.log(error);
      });
  })
  .catch(err => console.log(err));
```
I'm facing two problems, i'll explain them one by one:

1. if I don't run the code with sudo, I get following error- `Error: cannot open device with path 0001:0025:00`. I need to develop a cli solution using the logic stated above, So is there a way I can do it without sudo?
2. The code only runs if I switch to node v6.4.0. For instance, if I switch to node v8.9.3 it will return the following error: `Module version mismatch. Expected 48, got 57`. So, is there a way to run it without switching to an older version of Node.js?

**Comment by gre** [comment]
this is using an old version/unmaintain version of the library, I would recommand to try with latest libraries, in your case:

```js
const TransportHid = require("@ledgerhq/hw-transport-node-hid").default;
const AppBtc = require("@ledgerhq/hw-app-btc").default;
const bip32 = require("bip32");

function getCompressPublicKey(publicKey) {
  let compressedKeyIndex;
  if (parseInt(publicKey.substring(128, 130), 16) % 2 !== 0) {
    compressedKeyIndex = "03";
  } else {
    compressedKeyIndex = "02";
  }
  const result = compressedKeyIndex + publicKey.substring(2, 66);
  return result;
}

TransportHid.create().then(transport => {
    if (!transport) return console.log("err: Unable to establish connection");
    var btc = new AppBtc(transport);

    btc
      .getWalletPublicKey("44'/0'/0'/0")
      .then(function(result) {
        console.log("Result\n:", result);
        let compressedKey = getCompressPublicKey(result.publicKey);

        publicKey = new Buffer(compressedKey, "hex");
        chaincode = new Buffer(result.chainCode, "hex");
        const a = bip32.fromPublicKey(publicKey, chaincode);

        console.log("xPub:", a.neutered().toBase58());
      })
      .catch(function(error) {
        console.log(error);
      });
  }).catch(err => console.log(err));
```

deps: 
```js
    "@ledgerhq/hw-app-btc": "^4.13.0",
    "@ledgerhq/hw-transport-node-hid": "^4.13.0",
    "babel-runtime": "^6.26.0",
    "bip32": "^0.1.0"
```


I just tested this code and works fine in my node v8.9.4

**Comment by ayush-techracers** [comment]
Thanks a lot, I also found a solution to my `sudo` problem, we can manage it on linux using udev rules. I used the following bash script:

```
#!/bin/bash
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2581\", ATTRS{idProduct}==\"1b7c\", MODE=\"0660\", GROUP=\"rails\"" >/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2581\", ATTRS{idProduct}==\"2b7c\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2581\", ATTRS{idProduct}==\"3b7c\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2581\", ATTRS{idProduct}==\"4b7c\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2581\", ATTRS{idProduct}==\"1807\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2581\", ATTRS{idProduct}==\"1808\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2c97\", ATTRS{idProduct}==\"0000\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2c97\", ATTRS{idProduct}==\"0001\", MODE=\"0660\", GROUP=\"rails\"" >>/etc/udev/rules.d/20-hw1.rules
udevadm trigger
udevadm control --reload-rules
```

**Comment by ayush-techracers** [comment]
Hi @gre ,
When I am trying to sign P2SH transaction from ledger using ledgerhq package then I gets.
{ Error
    at new TransportStatusError (node_modules/@ledgerhq/hw-transport/src/Transport.js:111:16)
    at TransportNodeHid._callee$ /node_modules/@ledgerhq/hw-transport/src/Transport.js:268:13)
    at tryCatch (/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
  name: 'TransportStatusError',
  message: 'Ledger device: Internal error, please report (0x6f01)',
  stack: 'Error\n    at new TransportStatusError (/node_modules/@ledgerhq/hw-transport/src/Transport.js:111:16)\n    at TransportNodeHid._callee$ (/node_modules/@ledgerhq/hw-transport/src/Transport.js:268:13)\n  at tryCatch (/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [asnext] (/node_modules/regenerator-runtime/runtime.js:114:21)\n    at step (/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n    at /node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13\n    at <anonymous>',
  statusCode: 28417,
  statusText: 'UNKNOWN_ERROR' }
So could you please suggest what might be the issue?

**Comment by ayush-techracers** [comment]
I will detail my approach further, so you can help me troubleshoot it:
I'm using Leadger Nano S for creating mulitisig (p2sh) transactions for Bitcoin and I'm consuming signP2SHTransaction for it. But when i broadcast the produced transaction it returns the error I mentioned in my message above.

```
const TransportHid = require("@ledgerhq/hw-transport-node-hid").default;
const AppBtc = require("@ledgerhq/hw-app-btc").default;
const bip32 = require("bip32");
const Bitcore = require("bitcore-lib");

function getCompressPublicKey(publicKey) {
  let compressedKeyIndex;
  if (parseInt(publicKey.substring(128, 130), 16) % 2 !== 0) {
    compressedKeyIndex = "03";
  } else {
    compressedKeyIndex = "02";
  }
  const result = compressedKeyIndex + publicKey.substring(2, 66);
  return result;
}

TransportHid.create().then(transport => {
    if (!transport) return console.log("err: Unable to establish connection");
    var btc = new AppBtc(transport);

    // creating transaction input ===>

    // walletClient is an instance of bitcore-wallet-client
    let derivedXPrivKey = walletClient.credentials.getDerivedXPrivKey(null);
    var xpriv = new Bitcore.HDPrivateKey(derivedXPrivKey);

    var privs = [];
    var derived = {};

    _.each(txp.inputs, i => {
      if (!derived[i.path]) {
        derived[i.path] = xpriv.deriveChild(i.path).privateKey;
        privs.push(derived[i.path]);
      }
    });

    var t = new Bitcore.Transaction();

    _.each(txp.inputs, i => {
      t.from(i, i.publicKeys, txp.requiredSignatures);
    });

    _.each(txp.outputs, o => {
      t.to(o.toAddress, o.amount);
    });

    t.change(txp.changeAddress.address);
    let txnHex = t.toString("hex");

    const txObj = await btc.splitTransaction(txnHex);

    let inputArr = [];

    inputArr.push(txObj);

    inputArr.push(txObj.outputs.length - 1); // I'm not sure this is correct

    // redeemScript is calculated using Bitcore, I have crosschecked it and I'm sure it is correct
    inputArr.push(redeemScripts);


    // Creating output script ===>

    // Not sure about this either
    const outputScript = btc.serializeTransactionOutputs(txObj).toString('hex');

    await btc.signP2SHTransaction([inputArr],
      [`48'/0'/0'/${accountIndex}`],
      outputScript
    ).then(async (signature) => {
        return signature;
      })
     .catch((err) => console.log(err));
  }).catch(err => console.log(err));
```

This signature is then fed to bitcore-wallet-client's `signTxProposal` it errors during post request to `bitcore-wallet-service`'s API endpoint- `'/v1/txproposals/' + txp.id + '/signatures/'`. 

Can you help me verify my strategy, or pinpoint what could have caused this error?

**Comment by jonathansmirnoff** [comment]
@gre I tried to test your code but I had an issue:
```
$ node getHardwareData.js 
/.../node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:355
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(path) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined

```

I double checked that babel is installed.
