### ISSUE TITLE
Failed to sign with Ledger device: U2F TIMEOUT

### ISSUE THREAD

**Issue by pointtoken** [LedgerHQ/ledgerjs#201]
I'm trying to use the basic example but with the @ledgerhq/hw-transport-u2f library. I'm getting the following timeout. Note that the Ledger is unlocked when I attempt to call this code. Note that I do not have a U2F extension installed. If that is indeed the issue, which I suspect it is, can you please update the docs to explain that and recommend an extension to be installed?

```
import Transport from "@ledgerhq/hw-transport-u2f";
import AppBtc from "@ledgerhq/hw-app-btc";

       async getBTCAddress() {
            let transport;
            try {
                 transport = await Transport.create();

            } catch (err) {
                console.log(err);
            }
            const btc = new AppBtc(transport);
            try {
                const result = await btc.getWalletPublicKey("44'/0'/0'/0/0");
                console.log( result.bitcoinAddress);
    
            } catch (Err) {
                console.log(Err);
            }
        }
```
Here is the error:
 

```
TransportError {name: "TransportError", message: "Failed to sign with Ledger device: U2F TIMEOUT", stack: "Error↵    at new TransportError (webpack-internal:…/../core-js/library/modules/es6.promise.js:79:30)", id: "U2F_5", originalError: Error: Sign failed
    at makeError (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:102:14)
…, …}id: "U2F_5"message: "Failed to sign with Ledger device: U2F TIMEOUT"name: "TransportError"originalError: Error: Sign failed
    at makeError (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:102:14)
    at cbChrome (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:277:14)
    at u2f.responseHandler_ (webpack-internal:///../../../../u2f-api/lib/google-u2f-api.js:343:3)
    at eval (webpack-internal:///../../../../u2f-api/lib/google-u2f-api.js:212:7)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at dispatchOnMessage (extensions::messaging:392:22)metaData: {type: "TIMEOUT", code: 5}__zone_symbol__currentTask: ZoneTask {_zone: Zone, runCount: 0, _zoneDelegates: null, _state: "notScheduled", type: "microTask", …}message: "Sign failed"stack: "Error: Sign failed↵    at makeError (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:102:14)↵    at cbChrome (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:277:14)↵    at u2f.responseHandler_ (webpack-internal:///../../../../u2f-api/lib/google-u2f-api.js:343:3)↵    at eval (webpack-internal:///../../../../u2f-api/lib/google-u2f-api.js:212:7)↵    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)↵    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)↵    at EventImpl.dispatch_ (extensions::event_bindings:387:35)↵    at EventImpl.dispatch (extensions::event_bindings:409:17)↵    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)↵    at dispatchOnMessage (extensions::messaging:392:22)"__proto__: Objectstack: "Error↵    at new TransportError (webpack-internal:///../../../../@ledgerhq/hw-transport/lib/Transport.js:134:16)↵    at wrapU2FTransportError (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:52:13)↵    at TransportU2F._callee2$ (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:202:23)↵    at tryCatch (webpack-internal:///../../../../regenerator-runtime/runtime.js:65:40)↵    at Generator.invoke [as _invoke] (webpack-internal:///../../../../regenerator-runtime/runtime.js:299:22)↵    at Generator.prototype.(anonymous function) [as throw] (webpack-internal:///../../../../regenerator-runtime/runtime.js:117:21)↵    at step (webpack-internal:///../../../../babel-runtime/helpers/asyncToGenerator.js:17:30)↵    at eval (webpack-internal:///../../../../babel-runtime/helpers/asyncToGenerator.js:30:13)↵    at run (webpack-internal:///../../../../core-js/library/modules/es6.promise.js:66:22)↵    at eval (webpack-internal:///../../../../core-js/library/modules/es6.promise.js:79:30)"__zone_symbol__currentTask: null__proto__: Error
    at Object.eval (webpack-internal:///../../../../@ledgerhq/hw-transport/lib/Transport.js:138:28)
    at eval (webpack-internal:///../../../../@ledgerhq/hw-transport/lib/Transport.js:501:30)
    at Object.../../../../@ledgerhq/hw-transport/lib/Transport.js (https://localhost:4200/vendor.bundle.js:31:1)
    at __webpack_require__ (https://localhost:4200/inline.bundle.js:55:30)
    at Object.eval (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:45:20)
    at eval (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:268:30)
    at Object.../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js (https://localhost:4200/vendor.bundle.js:23:1)
    at __webpack_require__ (https://localhost:4200/inline.bundle.js:55:30)
    at eval (webpack-internal:///../../../../../src/app/components/trezorimport/trezorimport.component.ts:8:85)
    at Object.../../../../../src/app/components/trezorimport/trezorimport.component.ts (https://localhost:4200/main.bundle.js:483:1)
```

**Comment by MortalKastor** [comment]
No extension is needed, but you have to use Chrome and set `Browser support` to on in the app settings on your device.

**Comment by pointtoken** [comment]
I updated to the latest firmware Secure element 1.4.2 and MCU 1.5 and the latest BTC app 1.2.8. I then realized that the latest firmware doesn't have the Fido U2F app installed, so I reinstalled that. Does it need some configuration? Anyway, I'm getting a new error message at least:

```
TransportError {name: "TransportError", message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE", stack: "Error↵    at new TransportError (webpack-internal:…/../core-js/library/modules/es6.promise.js:79:30)", id: "U2F_4", originalError: Error: Sign failed
    at makeError (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:102:14)
…, …}id: "U2F_4"message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE"name: "TransportError"originalError: Error: Sign failed
    at makeError (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:102:14)
    at cbChrome (webpack-internal:///../../../../u2f-api/lib/u2f-api.js:277:14)
    at u2f.responseHandler_ (webpack-internal:///../../../../u2f-api/lib/google-u2f-api.js:343:3)
    at eval (webpack-internal:///../../../../u2f-api/lib/google-u2f-api.js:212:7)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at dispatchOnMessage (extensions::messaging:392:22)stack: "Error↵    at new TransportError (webpack-internal:///../../../../@ledgerhq/hw-transport/lib/Transport.js:134:16)↵    at wrapU2FTransportError (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:52:13)↵    at TransportU2F._callee2$ (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:202:23)↵    at tryCatch (webpack-internal:///../../../../regenerator-runtime/runtime.js:65:40)↵    at Generator.invoke [as _invoke] (webpack-internal:///../../../../regenerator-runtime/runtime.js:299:22)↵    at Generator.prototype.(anonymous function) [as throw] (webpack-internal:///../../../../regenerator-runtime/runtime.js:117:21)↵    at step (webpack-internal:///../../../../babel-runtime/helpers/asyncToGenerator.js:17:30)↵    at eval (webpack-internal:///../../../../babel-runtime/helpers/asyncToGenerator.js:30:13)↵    at run (webpack-internal:///../../../../core-js/library/modules/es6.promise.js:66:22)↵    at eval (webpack-internal:///../../../../core-js/library/modules/es6.promise.js:79:30)"__zone_symbol__currentTask: null__proto__: Error
    at Object.eval (webpack-internal:///../../../../@ledgerhq/hw-transport/lib/Transport.js:138:28)
    at eval (webpack-internal:///../../../../@ledgerhq/hw-transport/lib/Transport.js:501:30)
    at Object.../../../../@ledgerhq/hw-transport/lib/Transport.js (https://localhost:4200/vendor.bundle.js:31:1)
    at __webpack_require__ (https://localhost:4200/inline.bundle.js:55:30)
    at Object.eval (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:45:20)
    at eval (webpack-internal:///../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js:268:30)
    at Object.../../../../@ledgerhq/hw-transport-u2f/lib/TransportU2F.js (https://localhost:4200/vendor.bundle.js:23:1)
    at __webpack_require__ (https://localhost:4200/inline.bundle.js:55:30)
    at eval (webpack-internal:///../../../../../src/app/components/trezorimport/trezorimport.component.ts:8:85)
    at Object.../../../../../src/app/components/trezorimport/trezorimport.component.ts (https://localhost:4200/main.bundle.js:483:1)
trezorimport.component.ts:49 
```

**Comment by pointtoken** [comment]
@MortalKastor Did you see this follow up response? Any ideas?

**Comment by pointtoken** [comment]
Same error :( 
![ledgererror](https://user-images.githubusercontent.com/31048320/44041599-0303525a-9ed3-11e8-8fba-6ef0a368d2a7.png)

**Comment by MortalKastor** [comment]
Just to be sure before investigating deeper, did you add the right [udev rules](https://github.com/LedgerHQ/udev-rules) for the device to work under Linux?
Are you able to use your device with MyEtherWallet/MyCrypto in the same environment?

**Comment by pointtoken** [comment]
Ah ha!  It was failing because I hadn't actually clicked the receive button in Ledger Live to generate an address, even thought I had the Bitcoin app installed. Perhaps you could bootstrap the Bitcoin app with an address when it is installed to the device?

**Comment by amougel** [comment]
@pointtoken Addresses are actually generated every time a call is made to get them. There is no internal memory of addresses so it is impossible that using another software beforehand might have had the impact you are implying.
