### ISSUE TITLE
btc testnet multi sign failed!

### ISSUE THREAD

**Issue by qiluge** [LedgerHQ/ledgerjs#244]
I use two btc public key from ledger to generate multi-sign address, and I send some coin to this address.
Then I call the signP2SHTransaction function, I get the follow err:
```
(node:15746) UnhandledPromiseRejectionWarning: Error: getTrustedInput: locktime & outputs is expected
    at Btc.getTrustedInput (/Users/yin/Downloads/node-test/node_modules/@ledgerhq/hw-app-btc/src/Btc.js:144:13)
    at /Users/yin/Downloads/node-test/node_modules/@ledgerhq/hw-app-btc/src/Btc.js:940:9
    at /Users/yin/Downloads/node-test/node_modules/@ledgerhq/hw-app-btc/src/utils.js:80:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at Object.<anonymous> (/Users/yin/Downloads/node-test/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
(node:15746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
the call code is 
```
const multiSign = async () => {
  const transport = await Transport.create();
  const btc = new AppBtc(transport);
  btc.signP2SHTransaction(
    [["7388a3a8d54ce51f22d0a191b2528fd7aec0e416694fee32d6e6e68343b882b8",
      1, "524104e64783a8ed6a72466bac5446bacd3ec6025383a95cfcd885bb9c5cb2b10b10f" +
      "807962af44a826e6c25f84bf61bbdf12ea9662d380ca2d82b7ccedd40c4b4ace44104e1b1f8ce" +
      "da01c6fef673e8aae41126ac63d8ff410e03b15a606d829fa942143e8655c9afdb51b6cb337f40998b" +
      "a35d091973540d03ef0df2e3a2fb54812d8d4352ae"]],
    ["0'/0/0"],
    "0100000001b882b84383e6e6d632ee4f6916e4c0aed78f52b291a1d0221fe54cd5a8a38873010000000" +
    "0ffffffff01404b4c00000000001976a9144dfe4da0bd7d303629c19545174601fa5440bba088ac00000000"
  ).then(result => {
    console.log("first", result);
    btc.signP2SHTransaction(
      [["7388a3a8d54ce51f22d0a191b2528fd7aec0e416694fee32d6e6e68343b882b8",
        1, "524104e64783a8ed6a72466bac5446bacd3ec6025383a95cfcd885bb9c5cb2b10b10f" +
        "807962af44a826e6c25f84bf61bbdf12ea9662d380ca2d82b7ccedd40c4b4ace44104e1b1f8ce" +
        "da01c6fef673e8aae41126ac63d8ff410e03b15a606d829fa942143e8655c9afdb51b6cb337f40998b" +
        "a35d091973540d03ef0df2e3a2fb54812d8d4352ae"]],
      ["0'/0/0"],
      result).then(result => {
      console.log("second", result);
    });
  });
};
```
Can anyone help me?

**Comment by qiluge** [comment]
the problem is the first arg "tx" should be a object and I pass a txHash,
![image](https://user-images.githubusercontent.com/19525062/48600453-db6d0c80-e9a6-11e8-8bb0-aefa50918cdc.png)
But how can I construct the tx object?

**Comment by qiluge** [comment]
I use the btc.splitTransaction to generate tx and I meet another error
```
(node:103616) UnhandledPromiseRejectionWarning: Error
    at new TransportStatusError (G:\js workdspace\Ledger test\node_modules\@ledgerhq\hw-transport\src\Transport.js:111:16)
    at TransportNodeHid._callee$ (G:\js workdspace\Ledger test\node_modules\@ledgerhq\hw-transport\src\Transport.js:273:13)
    at tryCatch (G:\js workdspace\Ledger test\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (G:\js workdspace\Ledger test\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (G:\js workdspace\Ledger test\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (G:\js workdspace\Ledger test\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at G:\js workdspace\Ledger test\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```
And the error code is 27264 of these code 
![image](https://user-images.githubusercontent.com/19525062/48601214-f7be7880-e9a9-11e8-843c-76905c461909.png)
what is means of 27264?
![image](https://user-images.githubusercontent.com/19525062/48601250-13c21a00-e9aa-11e8-8989-17addde03ab2.png)

**Comment by qiluge** [comment]
reference to https://github.com/LedgerHQ/ledgerjs/issues/248
