### ISSUE TITLE
Cann't import the @ledgerhq/hw-transport-node-hid

### ISSUE THREAD

**Issue by zhangchiqing** [LedgerHQ/ledgerjs#266]
I'm trying to connect ledger in node:

```
yarn add @ledgerhq/hw-transport-node-hid
```

But the following code would throw:
```
var TransportNodeHid = require("@ledgerhq/hw-transport-node-hid");
```

Error logs:
```
/Users/leo/git/ledger/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:355
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(path) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/leo/git/ledger/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:355:50
    at /Users/leo/git/ledger/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:394:6
    at Object.<anonymous> (/Users/leo/git/ledger/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:398:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Node Version: v10.14.2
@ledgerhq/hw-transport-node-hid version: 4.33.3

Did I miss anything?

**Comment by gre** [comment]
the current limitation is you need to depend on `babel-polyfill` and do `import "babel-polyfill"` OR `require("babel-polyfill")` at the beginning of your JS entry point. 

e.g. https://github.com/LedgerHQ/ledgerjs/blob/5553717ec398d01e869f1b629f45f032f661a76a/packages/test/src/index-browser.js#L1

**Comment by zhangchiqing** [comment]
It works. Thanks!
