### ISSUE TITLE
Error installing in Ubuntu 18.04.1 - Electron v2.0.16

### ISSUE THREAD

**Issue by WilsonPhoo** [LedgerHQ/ledgerjs#330]
Error while using yarn

```
Error: /usr/bin/node exited with code 1
Output:
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:
error /home/user/Desktop/electron-app/app/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/user/Desktop/electron-app/app/node_modules/node-hid
Output:
prebuild-install WARN install No prebuilt binaries found (target=2.0.16 runtime=electron arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.10.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/user/Desktop/electron-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Desktop/electron-app/app/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Desktop/electron-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.electron-gyp/iojs-2.0.16/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.electron-gyp/iojs-2.0.16',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/Desktop/electron-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.electron-gyp/iojs-2.0.16/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Desktop/electron-app/app/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/Desktop/electron-app/app/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.
hidapi.target.mk:101: recipe for target 'Release/obj.target/hidapi/hidapi/linux/hid.o' failed
make: Leaving directory '/home/user/Desktop/electron-app/app/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/linux/hid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/Desktop/electron-app/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/home/user/Desktop/electron-app/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/Desktop/electron-app/app/node_modules/node-hid
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.childProcess.once.code (/home/user/Desktop/electron-app/node_modules/builder-util/src/util.ts:254:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at installOrRebuild (/home/user/Desktop/electron-app/node_modules/app-builder-lib/out/util/yarn.js:68:17)
    at /home/user/Desktop/electron-app/node_modules/electron-builder/src/cli/install-app-deps.ts:56:9
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (/home/user/Desktop/electron-app/node_modules/electron-builder/out/cli/install-app-deps.js:174:17)
    at then (/home/user/Desktop/electron-app/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (/home/user/Desktop/electron-app/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/home/user/Desktop/electron-app/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/home/user/Desktop/electron-app/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/home/user/Desktop/electron-app/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/home/user/Desktop/electron-app/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
```

**Comment by meriadec** [comment]
Given the stacktrace, error happen on `node-hid` installation, no prebuilt are found for your config so the postinstall script tries to build the lib from source, and fails because `libudev.h` is missing.

Should be fixed by installing [libudev-dev](https://packages.ubuntu.com/fr/trusty/libudev-dev).
