### ISSUE TITLE
Running ledgerjs-examples

### ISSUE THREAD

**Issue by praveenbm5** [LedgerHQ/ledgerjs#357]
I am a total newbie here and I am unable to figure out how to run the ledgerjs-examples. basic-u2f-react example to be specific. Any pointers will be greatly helpful.

And some docsumentation in the ledgerjs-examples repository will be super helpful.

**Comment by gre** [comment]
i've just added a README in https://github.com/LedgerHQ/ledgerjs-examples/tree/master/basic-u2f-react 

thanks

**Comment by praveenbm5** [comment]
Hey Gre,

I am now getting a blank page in the browser when I run "yarn start" and javascript error in browser -> development tools -> console

Uncaught ReferenceError: _regeneratorRuntime is not defined
    at new App (index.js:11)
    at constructClassInstance (react-dom.development.js:11222)
    at updateClassComponent (react-dom.development.js:14346)
    at beginWork (react-dom.development.js:15222)
    at performUnitOfWork (react-dom.development.js:18789)
    at workLoop (react-dom.development.js:18829)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:18061)

**Comment by praveenbm5** [comment]
To explain it all...

When I run "yarn" afresh after downloading files..

I get the following warining:

warning " > babel-preset-react-app@3.1.2" has unmet peer dependency "babel-runtime@^6.23.0"

So I added "babel-runtime": "^6.23.0" to dependencies in package.json

After that I got this error on "yarn start"

/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/index.js: Cannot read property 'key' of undefined
    at new PluginPass (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/babel-core/lib/transformation/plugin-pass.js:37:24)
    at initCloneByTag (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_initCloneByTag.js:60:14)
    at baseClone (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_baseClone.js:128:16)
    at /home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_baseClone.js:166:30
    at arrayEach (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_baseClone.js:160:3)
    at /home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_baseClone.js:166:30
    at arrayEach (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_baseClone.js:160:3)
    at /home/praveen/Workspace/ledgerjs-examples-master/basic-u2f-react/node_modules/lodash/_baseClone.js:166:30

So I replaced the following

state = {
    address: null,
    error: null
  };

with 

constructor (props) {
    super(props)
    this.state = { 
      address: null,
      error: null
    };
  }

And then the error discussed in the previous comment show up in Browser -> Console

Uncaught ReferenceError: _regeneratorRuntime is not defined
at new App (index.js:11)
at constructClassInstance (react-dom.development.js:11222)
at updateClassComponent (react-dom.development.js:14346)
at beginWork (react-dom.development.js:15222)
at performUnitOfWork (react-dom.development.js:18789)
at workLoop (react-dom.development.js:18829)
at HTMLUnknownElement.callCallback (react-dom.development.js:149)
at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
at invokeGuardedCallback (react-dom.development.js:256)
at replayUnitOfWork (react-dom.development.js:18061)
