### ISSUE TITLE
Error: Cannot find module 'usb'

### ISSUE THREAD

**Issue by xzjcool** [LedgerHQ/ledgerjs#364]
I use electron and  create-react-app. once i use @ledgerhq/hw-transport-node-hid. i got the error. i checked the source code. error occured in `./node_modules/@ledgerhq/hw-transport-node-hid/lib/listenDevices.js`

i have installed the usb package. what my cause this?

**Comment by gre** [comment]
when are you import/require-ing `@ledgerhq/hw-transport-node-hid` ? it must not be in the renderer code but in the main thread / dedicated thread.

**Comment by xzjcool** [comment]
yes. i import `@ledgerhq/hw-transport-node-hid` in renderer code right now. ok ,i will try in main thread. thanks

**Comment by xzjcool** [comment]
i try to use `@ledgerhq/hw-transport-node-hid` in main thread. but i stuck in the error `App threw an error during load
[1] Error: The module '/Users/xiezongjiang/binance/web-wallet/node_modules/usb/src/binding/usb_bindings.node'
[1] was compiled against a different Node.js version using
[1] NODE_MODULE_VERSION 69. This version of Node.js requires
[1] NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
[1] the module (for instance, using `npm rebuild` or `npm install`).
[1]     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
[1]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
[1]     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
[1]     at Module.load (internal/modules/cjs/loader.js:602:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:533:3)
[1]     at Module.require (internal/modules/cjs/loader.js:640:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.<anonymous> (/Users/xiezongjiang/binance/web-wallet/node_modules/usb/usb.js:5:38)
[1]     at Object.<anonymous> (/Users/xiezongjiang/binance/web-wallet/node_modules/usb/usb.js:526:3)`

any ideas about this?

**Comment by xzjcool** [comment]
```
App threw an error during load
[1] Error: The module '/Users/xzjcool/ledgerClient/node_modules/usb/src/binding/usb_bindings.node'
[1] was compiled against a different Node.js version using
[1] NODE_MODULE_VERSION 69. This version of Node.js requires
[1] NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
```
i import this module in main thread, but i got the error
any ideas about this error?

**Comment by meriadec** [comment]
As `node-hid` is a native dep, it has to be compiled against the same Node.js version that your electron version uses. To do that:

```
# install electron-builder
yarn add electron-builder --dev

# rebuild native deps with electron
./node_modules/.bin/electron-builder install-app-deps
```

it is advised to add a `package.json` script that does that, you can even launch it as postinstall command.

see here for more infos: https://webpack.electron.build/dependency-management#installing-native-node-modules

**Comment by xzjcool** [comment]
`"postinstall": "electron-builder install-app-deps",`
i have the postinstall script in package.json. what the same node version means.

**Comment by xzjcool** [comment]
solved by npm rebuild. thanks

**Comment by xzjcool** [comment]
> when are you import/require-ing `@ledgerhq/hw-transport-node-hid` ? it must not be in the renderer code but in the main thread / dedicated thread.

if i set nodeIntegration to true, can i use `@ledgerhq/hw-transport-node-hid` in renderer thread?

**Comment by gre** [comment]
I didn't try but I would highly recommend not to. Node-hid have some sync function so you are likely blocking the renderer by doing that which will cause bad performance and lags
