### ISSUE TITLE
 Failed to initialize libusb while use hw-app-xtz

### ISSUE THREAD

**Issue by qiluge** [LedgerHQ/ledgerjs#462]
hello, I saw the  ledger support tezos at https://github.com/obsidiansystems/ledgerjs/tree/tezos/packages/hw-app-xtz.

And I install the package ```@obsidiansystems/hw-app-xtz```.

But when I run the example code to get address, there are an error: 
```
Failed to initialize libusb.
/mnt/g/工作/tezos/xtz-ledger-test/node_modules/@obsidiansystems/hw-app-xtz/lib/Tezos.js:69
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(path, boolDisplay, curve, apdu // TODO specify
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /mnt/g/工作/tezos/xtz-ledger-test/node_modules/@obsidiansystems/hw-app-xtz/lib/Tezos.js:69:50
    at /mnt/g/工作/tezos/xtz-ledger-test/node_modules/@obsidiansystems/hw-app-xtz/lib/Tezos.js:120:6
    at Object.<anonymous> (/mnt/g/工作/tezos/xtz-ledger-test/node_modules/@obsidiansystems/hw-app-xtz/lib/Tezos.js:361:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```
![image](https://user-images.githubusercontent.com/19525062/75135421-70b78e80-571c-11ea-8d08-242f88834cdb.png)

and then I use babel to run the file, like this:
![image](https://user-images.githubusercontent.com/19525062/75135462-888f1280-571c-11ea-81ac-1b0388043254.png)
It display 
```
Failed to initialize libusb.
Promise { <pending> }
```

I am so sorry to make issue here, but I cannot contact the developer @obsidiansystems, and his repo doesn't open issue feature.

**Comment by qiluge** [comment]
hello, I may have found the reason. I use WSL to develope, and dependency in node_modules composed from different OS, some from windows npm install, some from WSL npm install. After I clean node_modules and re-run npm install in windows, it works.
