### ISSUE TITLE
SECURITY_STATUS_NOT_SATISFIED

### ISSUE THREAD

**Issue by maede71** [LedgerHQ/ledgerjs#550]
Hi, I have an error in this line: 
const result = await btc.getWalletPublicKey("44'/0'/0'/0/0");
return result.bitcoinAddress;

Error
    at new TransportStatusError (C:\Users\Sazegar\Desktop\Arz4u\node_modules\@ledgerhq\errors\dist\index.cjs.js:289:18)
    at TransportNodeHid.Transport.send (C:\Users\Sazegar\Desktop\Arz4u\node_modules\@ledgerhq\hw-transport\lib\Transport.js:59:15)
    at async getWalletPublicKey (C:\Users\Sazegar\Desktop\Arz4u\node_modules\@ledgerhq\hw-app-btc\lib\getWalletPublicKey.js:40:20)
    at async Btc.getWalletPublicKey (C:\Users\Sazegar\Desktop\Arz4u\node_modules\@ledgerhq\hw-transport\lib\Transport.js:240:16)
    at async getBtcAddress (C:\Users\Sazegar\Desktop\Arz4u\test.js:36:19) {
  message: 'Ledger device: Security not satisfied (dongle locked or have invalid access rights) (0x6982)',
  statusCode: 27010,
  statusText: 'SECURITY_STATUS_NOT_SATISFIED'
}

**Comment by gre** [comment]
- is the device unlocked?
- is the device on the Bitcoin app ? (this is a bitcoin derivation path, only Bitcoin will allow to derivate the address there)

Thanks

**Comment by maede71** [comment]
Thankful. I must choose Bitcoin on my device.
